### ISSUE TITLE
ShortAnswer Text Box Disappears

### ISSUE THREAD

**Issue by bowmanat** [inducer/relate#513] opened 2018-03-25 20:32 UTC
When an answer is submitted to a ShortAnswer question, RELATE will accept the input and grade it correctly.  However, the text box disappears, so students cannot see their answer and cannot immediately submit a new answer.  To bring the text box back so that they can try again, students must click 'Submit Answer for Feedback', after which RELATE will bring back the text box with the usual error message about not submitting an empty answer.

**Comment by inducer** [comment] 2018-03-25 21:14
@dzhuang This seems to have been caused by e0f3caefe8a8415673bfdebb9d2c260cbe937924.

@bowmanat As a UIUC operations matter, I have reverted the instance to not use that commit.

**Comment by inducer** [comment] 2018-03-25 21:14
I should add that I was able to reproduce the issue.

**Comment by dzhuang** [comment] 2018-03-26 01:16
Sorry, I'll fix this ASAP.

**Comment by dzhuang** [comment] 2018-03-26 03:35
@bowmanat Can you give more details on the issue? For example, a (simplified) question markup and the correct/incorrect answer. Thanks. CC @inducer

**Comment by dzhuang** [comment] 2018-03-26 03:56
I imaging the bug was related to` InlineMultiQuestion`, am I right? 

However, with the sample repo, I can't reproduce that.

**Comment by dzhuang** [comment] 2018-03-26 04:39
(I can't reproduct that before fixing #513.)

**Comment by inducer** [comment] 2018-03-26 04:39
No, this was with a `TextQuestion`. Simply saving the answer (not submitting) was enough to make the text box disappear on the sample repo.

**Comment by dzhuang** [comment] 2018-03-26 04:47
> No, this was with a TextQuestion

Am I missing something? Saving will also result in 500, for the case you suggested in #514, i.e., students won't have chance to click 'Submit Answer for Feedback'. And that was fixed now.

**Comment by dzhuang** [comment] 2018-03-26 04:57
> However, the text box disappears, so students cannot see their answer and cannot immediately submit a new answer. To bring the text box back so that they can try again, students must click 'Submit Answer for Feedback', after which RELATE will bring back the text box with the usual error message about not submitting an empty answer.

How was that possible? @inducer

**Comment by dzhuang** [comment] 2018-03-26 04:58
If that's the case, I don't think 
> As a UIUC operations matter, I have reverted the instance to not use that commit.

will solve the issue.

**Comment by dzhuang** [comment] 2018-03-26 05:01
Or, did you use some mechanism to prevent 500 by not rendering the buggy form? That might explain why the form was hidden.

**Comment by bowmanat** [comment] 2018-03-26 13:51
@dzhuang I'm unable to reproduce the issue at this point since it has been fixed for UIUC.  It seemed that it was affecting every TextQuestion, but did not affect InlineMultiQuestions.

**Comment by dzhuang** [comment] 2018-03-26 16:25
@bowmanat Thanks for the reply! Do you think it's fixed? @inducer

**Comment by inducer** [comment] 2018-03-28 16:35
Can't reproduce on 0238d403. Let's call it fixed. Thanks for taking a look, @dzhuang!

**Closed by inducer** 2018-03-28 16:35 UTC
