### ISSUE TITLE
Grading stats usability

### ISSUE THREAD

**Issue by eecarrier** [inducer/relate#182] opened 2016-03-02 22:29 UTC
The grading statistics link from the page for the specific grading opportunity appears to be broken and goes to a mostly blank page with no info shown.
[Screen Shot 2016-03-02 at 4.29.08 PM.pdf](https://github.com/inducer/relate/files/155814/Screen.Shot.2016-03-02.at.4.29.08.PM.pdf)

**Comment by inducer** [comment] 2016-03-03 00:57
Nope, that's as intended. What "grading statistics" means here is "which grader has graded how many problems". Since it doesn't look like there was any hand-grading involved on your midterm 1, an empty page is, technically, the right thing to show.

What you're looking for is likely this:
https://relate.cs.illinois.edu/course/cs357-sp16/flow-analytics/midterm1/

Now, from a usability perspective, I can see two changes making sense:

* First, instead of an (agreed, admittedly broken-looking) empty page, it should show a message like "no human-graded problems found".
* Second, there should probably be a link to the "analytics" page from the gradebook.

I'll leave this bug open to track those two changes.

**Comment by inducer** [comment] 2016-03-03 07:35
Should be fixed now.

**Closed by inducer** 2016-03-03 07:35 UTC
