### ISSUE TITLE
Dark mode issues / dark mode toggle needed

### ISSUE THREAD

**Issue by peepeetee** [inducer/relate#1104] opened 2024-10-10 04:01 UTC
1. need a dark mode toggle, so I can turn dark mode off without changing my browser dark mode
2. coding text coloring doesn't play well with dark mode: 
![140ea2a8aa2dc3d9390fbebc4c7ea4616631ac9b](https://github.com/user-attachments/assets/b0009f0a-34e0-4f94-8df0-ae7157a9ebff)
The line currently being worked on is unreadable with this colour scheme

**Comment by inducer** [comment] 2024-10-10 13:25
Dupe of #1091, #1084.

**Closed by inducer** 2024-10-10 13:25 UTC
