### ISSUE TITLE
username, firstname and lastname need rules.

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#6] opened 2015-03-15 09:35 UTC
when I turn on the option `STUDENT_SIGN_IN_VIEW = "course.auth.sign_in_by_user_pw"`, many of the error comes from my students who are signing up using non-roman characters or have space in their usernames. Maybe you can:
 * add form validation to ensure that they must use english letters (or numbers, underscore) without space in their username  
 * add form validation to ensure that first name and last name accept english letters only (it's alright for me).

Thanks.

**Comment by inducer** [comment] 2015-03-15 14:40
What's the issue with first/last? I don't see how either of those would cause an issue.

**Comment by dzhuang** [comment] 2015-03-15 17:10
Because I only see their name as "?" when they input with Chinese. Or let
me look into the issue later. Thanks.

2015-03-15 22:40 GMT+08:00 Andreas Klöckner <notifications@github.com>:

**Comment by inducer** [comment] 2015-03-16 06:23
I can't reproduce either issue you mention:

* I copy-paste some Chinese characters into first/last, and I wasn't able to find a place where they aren't shown correctly.
* I tried a user name with spaces in it, and I could sign in without a problem. I also couldn't find anything else that malfunctioned.

I'll close this for now. Feel free to reopen if you can provide a way to reproduce the issues you are seeing.

**Closed by inducer** 2015-03-16 06:23 UTC

**Comment by dzhuang** [comment] 2015-03-16 11:00
What a shame of me, I should have google the issue before posting. The raised error is `Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='`, and the solution was disccussed in: http://stackoverflow.com/questions/1008287/illegal-mix-of-collations-mysql-error

Thank you for your patience!

**Comment by inducer** [comment] 2015-03-17 05:49
No problem at all. Glad it got figured out.
