### ISSUE TITLE
Feature: allow non-superuser instructors to edit events (kind of urgent)

### ISSUE THREAD

**Issue by ifaintad** [inducer/relate#361] opened 2017-09-13 06:02 UTC
An instructor has no way/permission to view events he've just created, let alone edit, except that he is granted superuser permissions of the site (solely staff is not enough).
Can you solve the problem? I think it's reasonable to assume non-superuser instructors should have partial permissions for admin though not full control.

**Comment by inducer** [comment] 2017-09-13 13:28
There's a merge request/branch for that:

https://gitlab.tiker.net/inducer/relate/merge_requests/42

I have not yet had the time to review it, but you could likely just merge that for your local instance.

**Comment by inducer** [comment] 2017-09-13 13:28
Closing because it's a duplicate of #322.

**Closed by inducer** 2017-09-13 13:28 UTC

**Comment by ifaintad** [comment] 2017-09-14 01:25
Thank you!

**Comment by dzhuang** [comment] 2017-09-14 01:33
Just find I was using a testing account to report this. Thanks again.

**Comment by inducer** [comment] 2017-09-14 01:43
And here I was, all excited that another user showed up out of the woodwork. ☺

**Comment by dzhuang** [comment] 2017-09-14 01:49
You are so modest! :joy:
