### ISSUE TITLE
Brocken Latex, fails to render \begin{align}

### ISSUE THREAD

**Issue by yslan** [inducer/relate#1155] opened 2024-10-25 16:10 UTC
As title, see examples below

```
problem-bank/quiz-questions/eigenvalue/qr-iteration-properties.yml
```

or "correct answer" in hw3 [Link](https://relate.cs.illinois.edu/course/cs450-f24/flow-session/896537/0/)
```
problem-bank/homework-problems/linear_systems/theory-cond-nonsing.yml
```

Suspecting this commit: 
https://github.com/inducer/relate/commit/37190579ca2a2532ae2ca2c660d4d2f29ce54f0b

**Comment by inducer** [comment] 2024-10-25 16:20
Dupe of #1153? Looking into it.

**Comment by inducer** [comment] 2024-10-25 16:43
It is a dupe.

**Closed by inducer** 2024-10-25 16:43 UTC
